version: '3'
name: library

services:
      database:
            container_name: database
            build:
                  context: .
                  dockerfile: mysql.dockerfile
                  args:
                        - ROLE=production
                        - MYSQL_DATABASE=${MYSQL_DATABASE}
                        - MYSQL_USER=${MYSQL_USER}
                        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            ports:
                  - '${MYSQL_PORT}:3306'
            volumes:
                  - db-data:/var/lib/mysql/
            networks:
                  - app-network
      server:
            container_name: server
            env_file:
                  - .env.production
            build:
                  context: .
                  dockerfile: server.dockerfile
            depends_on:
                  - database
            volumes:
                  - ./:/app
            ports:
                  - '${SERVER_PORT}:8080'
            networks:
                  - app-network

volumes:
      db-data: ~

networks:
      app-network:
            driver: bridge