export default [
      {
            rules: {
                  'constructor-super': ['error'],
                  'for-direction': ['error'],
                  'getter-return': ['error'],
                  'no-cond-assign': ['error'],
                  'no-constructor-return': ['error'],
                  'no-dupe-args': ['error'],
                  'no-dupe-class-members': ['error'],
                  'no-dupe-keys': ['error'],
                  'no-duplicate-case': ['error'],
                  'no-ex-assign': ['error'],
                  'no-inner-declarations': ['error'],
                  'no-new-native-nonconstructor': ['error'],
                  'no-self-assign': ['error'],
                  'no-unused-vars': ['error'],
                  'block-scoped-var': ['error'],
                  camelcase: ['error'],
                  eqeqeq: ['error'],
                  'func-name-matching': ['error'],
                  'func-names': ['error'],
                  'func-style': ['error', 'declaration'],
                  'no-empty': ['error'],
                  'no-undefined': ['error'],
                  'no-var': ['error'],
                  'prefer-template': ['warn'],
            },
      },
];
